### ISSUE TITLE
Allow use in Docker

### ISSUE THREAD

**Issue by coderanger** [hw-cookbooks/runit#100]
It would be nice if there was a resource-level override for "yes I know I'm inside Docker but I promise everything will be okay". My [current hack](https://github.com/poise/poise-service-runit/blob/master/lib/poise_service/providers/runit.rb#L73-L82) is more fragile than I would like.

**Comment by ge1st** [comment]
+1 I'm using docker for test-kitchen integration tests and it'd be awful nice to be able to use runit services in our cookbooks without hackery.

**Comment by coderanger** [comment]
New URL to my hack is https://github.com/poise/poise-service-runit/blob/master/lib/poise_service/runit/provider.rb#L101-L112

**Comment by jsirex** [comment]
+1 For this

**Comment by dalehamel** [comment]
Looks like the main issue was introduced here:

https://github.com/hw-cookbooks/runit/pull/61

There are no tests for this that I can see, and I'm not sure the issue that it was trying to solve for is still relevant - I can run within docker easily enough.

Because this check is skipped by default though, it introduces a race condition when running chef inside of docker (or really, any container) that is quite annoying.

I would suggest getting rid of this docker check altogether, as there's no valid reason why runit wouldn't work inside docker. By just setting the 'inside_docker?' to return false always, my chef run continues along happily.

If we're worried about compatibility, we could at least add a flag like "node['runit']['poll_supervise_files']" that would force this, even if in docker.

**Comment by dalehamel** [comment]
FYI, my 'fix' for this is here https://github.com/dalehamel/runit/commit/97b072c7728a10139945c51a367545f5e6712b5b
