### ISSUE TITLE
Create service but do not start it?

### ISSUE THREAD

**Issue by jviney** [hw-cookbooks/runit#66]
Is it possible to create a new service but not attempt to start it? I'm creating services that will only be brought up in certain circumstances.

I think what I'm after is an ```action :configure``` option.

Cheers.

**Comment by jslusher** [comment]
It appears that code isn't in the cookbook yet? I think it would be a great idea to have something like that. I'm currently struggling with a deployment because the runit service tries to start before everything is in place. It's because of seperate capistrano task that has to run before runit can work.

**Comment by jslusher** [comment]
At any rate when I try using action :configure, I get an error telling me I can't use it.

**Comment by jtimberman** [comment]
This is implemented as the `:create` [action](https://github.com/hw-cookbooks/runit/blob/develop/libraries/provider_runit_service.rb#L83-L88) in version 1.5.14.
