### ISSUE TITLE
runit_service :enable not idempotent.

### ISSUE THREAD

**Issue by withnale** [hw-cookbooks/runit#77]
Is it possible to ensure that runit runs idempotently?

i.e. if I have fully deployed a server and there are no changes made to the cookbook, 'knife node lastrun' should not show runit_services being enabled on each and every run?

**Comment by jtimberman** [comment]
Looking into this.

**Comment by jtimberman** [comment]
After initial investigation, it's not clear to me why the resource is being updated every run. The output appears inline with the link resource. For example from the `plain-defaults` service in the `runit_test::service` recipe:

```
Recipe: runit_test::service
  * runit_service[plain-defaults] action enable
  Recipe: <Dynamically Defined Resource>
    * directory[/etc/sv/plain-defaults] action create (up to date)
    * template[/etc/sv/plain-defaults/run] action create (up to date)
    * directory[/etc/sv/plain-defaults/log] action create (up to date)
    * directory[/etc/sv/plain-defaults/log/main] action create (up to date)
    * template[/etc/sv/plain-defaults/log/run] action create (up to date)
    * template[/etc/sv/plain-defaults/log/config] action create (up to date)
    * link[/etc/init.d/plain-defaults] action create (up to date)
    - configure service runit_service[plain-defaults]
```

**Comment by jtimberman** [comment]
That's the converge_by block, it's not specifically the link resource actually.

**Comment by dblessing** [comment]
Isn't this happening at https://github.com/hw-cookbooks/runit/blob/develop/libraries/provider_runit_service.rb#L93 ? The comment even says it should run every time even though that seems unnecessary. Can this be wrapped in a conditional to check resource existence first?

**Comment by jtimberman** [comment]
Everything done by that method is a resource. It will get executed every run but convergence is checked for each of the embedded resources in their own way.

**Comment by dblessing** [comment]
If just one of those resources isn't idempotent will it cause this issue?

**Comment by dblessing** [comment]
Total noob trying to dig in so sorry if I have silly questions.

**Comment by jtimberman** [comment]
The `configure_service` operates on the following resources:

* sv_dir - `directory`
* run_script - `template`
* log_dir - `directory`
* log_main_dir - `directory`
* default_log_dir - `directory`
* log_run_script - `file` or `template`. If `default_logger` is set, it's a `file` resource, otherwise it is a `template`.
* log_config_file - `template`
* env_dir - `directory`
* env_files - `file`.
* check_script - `template`
* finish_script - `template`
* control_dir - `directory`
* control_signal_files - `template`
* lsb_init - `template` or `link`. If the platform is Debian, this is rendered as a `template`. Otherwise it is a `link` resource.

To be clear about the behavior here, this statement is accurate:

> Chef takes idempotent actions on resources to converge them to the desired state.

To clarify idempotent vs converge: idempotent generally means that multiple application of the same action does not change the outcome, whereas converge generally means over time bring the state to that which is desired. In Chef, converge means "test the state of this thing, and repair it if it is not in the state declared." Many people discussing configuration management these days say idempotent when they really mean convergent.

So what's going on here is the `enable` action converges by configuring the service based on a number of convergent resources (template, file, directory, link). It needs to do this because all of these resources might be changed by an external force, requiring Chef to "repair" their state. This is actually idempotent, and it is also convergent, as no system changes are made unless they need to be based on the use of Chef resources for those changes. This gets executed every time inside the `converge_by` block, which is why this is reporting output on each run.

One approach that might help here is the use of [inline resources](https://docs.chef.io/lwrp.html#inline-compile-mode), a la `use_inline_resources` from `Chef::Provider::LWRPBase`, but that would involve a fairly significant refactor and require a lot of testing to ensure that compatibility is maintained.

**Comment by slyness** [comment]
Closing this. Shout out to @jtimberman :facepunch:
